const SYNC_INCREMENT = 'SYNC_COUNTER/INCREMENT';
const SYNC_DECREMENT = 'SYNC_COUNTER/DECREMENT';

const ASYNC_INCREMENT = 'ASYNC_COUNTER/INCREMENT';
const ASYNC_DECREMENT = 'ASYNC_COUNTER/DECREMENT';

export {
  SYNC_INCREMENT,
  SYNC_DECREMENT,
  ASYNC_DECREMENT,
  ASYNC_INCREMENT,
};
